# Generated by Django 5.1.6 on 2025-03-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userotp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
